language: python
python:
    - "2.7"
    - "3.4"
    - "3.5"
addons:
  apt:
    packages:
    - freetds-dev
install:
  - pip install -r requirements.txt
  - pip install -r tox-requirements.txt
script:
  - coverage run -m pytest --strict mssqlcli
after_success:
  - coveralls
